# Generated by Django 5.2.3 on 2025-07-06 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_and_more'),
        ('properties', '0004_property_agent'),
        ('tenants', '0004_alter_tenant_current_unit'),
        ('units', '0005_alter_unit_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account_reference',
            field=models.CharField(default='LEGACY-REF', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('RENT', 'Rent Payment'), ('DEPOSIT', 'Deposit'), ('UTILITY', 'Utility Payment')], default='RENT', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='units.unit'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash')], default='MPESA', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='LEGACY-ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='receipt_number',
            field=models.CharField(default='LEGACY-RECEIPT', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('reference_number', models.CharField(max_length=100)),
                ('transfer_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('verification_status', models.CharField(max_length=20)),
                ('ipn_response', models.JSONField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_details', to='payments.payment')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paybill_number', models.CharField(max_length=20)),
                ('account_reference', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('result_code', models.CharField(max_length=20)),
                ('result_description', models.TextField()),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_details', to='payments.payment')),
            ],
        ),
    ]
