# Generated by Django 5.2.3 on 2025-07-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_account_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account_reference',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
