# Generated by Django 5.2.3 on 2025-07-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_account_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
