# Generated by Django 5.2.3 on 2025-06-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='phone',
        ),
    ]
