# Generated by Django 5.2.3 on 2025-06-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_remove_agent_email_remove_agent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='is_active',
        ),
    ]
