# Generated by Django 5.2.3 on 2025-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_agent_is_active'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='additional_contacts',
            field=models.JSONField(default=list, help_text='Array of additional phone numbers'),
        ),
        migrations.AddField(
            model_name='agent',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='properties',
            field=models.ManyToManyField(related_name='managing_agents', to='properties.property'),
        ),
        migrations.AddField(
            model_name='agent',
            name='registration_number',
            field=models.CharField(blank=True, help_text='CR12 or business ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Encrypted tax identification', max_length=100, null=True, unique=True),
        ),
    ]
