# Generated by Django 5.2.3 on 2025-07-01 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0005_remove_landlord_address_landlord_email_and_more'),
        ('lease', '0001_initial'),
        ('tenants', '0002_remove_tenant_email_remove_tenant_name_and_more'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='arrears',
            new_name='balance_due',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='actual_move_out_date',
            new_name='move_out_date',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='expected_move_out_date',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='unit',
        ),
        migrations.AddField(
            model_name='tenant',
            name='active_lease',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tenant', to='lease.lease'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='current_unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tenant', to='units.unit'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='For lease compliance', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_verification_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='lease_agreement_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_due_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, help_text='Formatted: "+1234567890"', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='proof_of_income_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='landlords.landlord'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAST', 'Past'), ('EVICTED', 'Evicted'), ('APPLICANT', 'Applicant')], default='APPLICANT', max_length=20),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=50)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('BANK', 'Bank Transfer'), ('CARD', 'Card Payment'), ('CASH', 'Cash')], max_length=10)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('LATE', 'Late'), ('PARTIAL', 'Partial')], max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
