# Generated by Django 5.2.3 on 2025-07-03 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_rename_arrears_tenant_balance_due_and_more'),
        ('units', '0003_alter_unit_unit_id_alter_unit_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='current_unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_unit', to='units.unit'),
        ),
    ]
