# Generated by Django 5.2.3 on 2025-07-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_current_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
