# Generated by Django 5.2.3 on 2025-07-29 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0006_remove_landlord_company_registration_number_and_more'),
        ('tenants', '0005_delete_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_groups', to='landlords.landlord')),
                ('tenants', models.ManyToManyField(related_name='groups', to='tenants.tenant')),
            ],
        ),
    ]
