# Generated by Django 5.2.3 on 2025-07-01 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_remove_property_description_and_more'),
        ('tenants', '0003_rename_arrears_tenant_balance_due_and_more'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unit',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='unit',
            name='lease_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='photos',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='unit',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='unit',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in square feet', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.CharField(blank=True, choices=[('2BR/2BA/OK', '2 Bedroom 2 Bathroom Open Kitchen'), ('2BR/3BA/CK', '2 Bedroom 3 Bathroom Closed Kitchen')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('OCCUPIED', 'Occupied'), ('VACANT', 'Vacant'), ('MAINTENANCE', 'Under Maintenance')], default='VACANT', max_length=20),
        ),
        migrations.CreateModel(
            name='UnitTenantHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_history', to='units.unit')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='unit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='rent_amount',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_type',
        ),
    ]
