# Generated by Django 5.2.3 on 2025-07-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_remove_property_description_and_more'),
        ('units', '0002_alter_unit_unique_together_unit_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'unit_id')},
        ),
    ]
