# Generated by Django 5.2.3 on 2025-07-03 11:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_agent'),
        ('tenants', '0004_alter_tenant_current_unit'),
        ('units', '0003_alter_unit_unit_id_alter_unit_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['property_fk', 'unit_number']},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unit',
            name='current_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='unit',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='unit',
            name='features',
            field=models.JSONField(default=dict, help_text='Additional unit features {"parking_spots": 2, "storage_unit": "B12"}'),
        ),
        migrations.AddField(
            model_name='unit',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='lease_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='property_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(default='TBD', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenities',
            field=models.JSONField(default=list, help_text='List of amenities ["balcony", "parking", etc]'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('2BR/2BA/OK', '2 Bedroom 2 Bathroom Open Kitchen'), ('2BR/3BA/CK', '2 Bedroom 3 Bathroom Closed Kitchen')], default='2BR/2BA/OK', max_length=20),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['current_tenant'], name='units_unit_current_6aafe7_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['lease_end_date'], name='units_unit_lease_e_328136_idx'),
        ),
        migrations.RemoveField(
            model_name='unit',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='property',
        ),
    ]
