# Generated by Django 5.2.3 on 2025-07-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_agent'),
        ('tenants', '0004_alter_tenant_current_unit'),
        ('units', '0004_alter_unit_options_alter_unit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property_fk', 'unit_number')},
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property_fk', 'status'], name='units_unit_propert_5c2765_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property_fk', 'type'], name='units_unit_propert_476283_idx'),
        ),
    ]
