# Generated by Django 5.2.3 on 2025-06-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_name_user_first_name_user_bio_user_city_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
