# Generated by Django 5.2.3 on 2025-06-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_facebook_url_remove_user_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='year_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
