# Generated by Django 5.2.3 on 2025-06-16 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='The agent responsible for this landlord.', limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_landlords', to=settings.AUTH_USER_MODEL),
        ),
    ]
