# Generated by Django 5.2.3 on 2025-06-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0002_landlord_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='phone',
        ),
    ]
