# Generated by Django 5.2.3 on 2025-06-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0003_remove_landlord_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='is_active',
        ),
    ]
