# Generated by Django 5.2.3 on 2025-07-01 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_additional_contacts_agent_city_and_more'),
        ('landlords', '0004_remove_landlord_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='address',
        ),
        migrations.AddField(
            model_name='landlord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='id_number',
            field=models.CharField(blank=True, help_text='Encrypted', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='landlord_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='last_tax_filing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='tax_filing_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landlord',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_landlords', to='agents.agent'),
        ),
    ]
