# Generated by Django 4.2.23 on 2025-07-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0005_remove_landlord_address_landlord_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='company_registration_number',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='email',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='name',
        ),
    ]
