# Generated by Django 5.2.3 on 2025-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_remove_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
