from rest_framework import viewsets
from rest_framework.permissions import AllowAny
from landlords.models import Landlord
from landlords.serializers import LandlordReadSerializer, LandlordWriteSerializer
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission

class LandlordViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated, RoleBasedPermission]
    
    def get_queryset(self):
        user = self.request.user
        queryset = Landlord.objects.select_related('user', 'agent')
        
        if user.is_superuser or user.role == 'admin':
            return queryset.all()
        elif user.role == 'agent':
            # Only return landlords associated with this agent
            return queryset.filter(agent__user=user)
        elif user.role == 'landlord':
            return queryset.filter(user=user)
        elif user.role == 'tenant':
            return queryset.filter(properties__units__current_tenant__user=user)
        return Landlord.objects.none()

    def get_serializer_class(self):
        if self.action in ['list', 'retrieve', 'create']:
            return LandlordReadSerializer
        return LandlordWriteSerializer

    def create(self, request, *args, **kwargs):
        response = super().create(request, *args, **kwargs)
        landlord = self.get_queryset().get(id=response.data['id'])
        serializer = LandlordReadSerializer(landlord)
        response.data = {
            'message': 'Landlord created successfully',
            'landlord': serializer.data
        }
        return response
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated
from accounts.permissions import RoleBasedPermission
from rest_framework.permissions import IsAuthenticated