# Generated by Django 5.2.3 on 2025-06-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanager',
            name='is_active',
        ),
    ]
