# Generated by Django 5.2.3 on 2025-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_remove_property_description_and_more'),
        ('property_manager', '0002_remove_propertymanager_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertymanager',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='assigned_properties',
            field=models.ManyToManyField(related_name='caretakers', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='contract_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='For after-hours emergencies', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='id_document_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='manager_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='shift_hours',
            field=models.JSONField(default=dict, help_text='Working hours schedule'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
